categories:
  Albatross: 0
  American_Goldfinch: 1
  anthuriam: 2
  frangipani: 3
  Marigold: 4
  Red_headed_Woodpecker: 5

data_folder: '/data3/ankit/Coursework/AIP/Assignment_1/assignment1_data/assignment1_data'